import Head from 'next/head'
import localFont from '@next/font/local';

import { NavBar, Hero, About, Menu, Wine, Events, Contact } from '@/components'

import menu from '@/static/menu.json';
import wines from '@/static/wines.json';

import { gsap } from "gsap";
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';

const brandonGrotesque = localFont({ 
  src: [
    {
      path: "../assets/fonts/Brandon_light.otf",
      weight: "300",
      style: "normal"
    },
    {
      path: "../assets/fonts/Brandon_light_it.otf",
      weight: "300",
      style: "italic"
    },
    {
      path: "../assets/fonts/Brandon_reg.otf",
      weight: "400",
      style: "normal"
    },
    {
      path: "../assets/fonts/Brandon_reg_it.otf",
      weight: "400",
      style: "italic"
    },
    {
      path: "../assets/fonts/Brandon_med.otf",
      weight: "500",
      style: "normal"
    },
    {
      path: "../assets/fonts/Brandon_med_it.otf",
      weight: "500",
      style: "italic"
    },
    {
      path: "../assets/fonts/Brandon_bld.otf",
      weight: "600",
      style: "normal"
    },
    {
      path: "../assets/fonts/Brandon_bld_it.otf",
      weight: "600",
      style: "italic"
    },
    {
      path: "../assets/fonts/Brandon_blk.otf",
      weight: "700",
      style: "normal"
    },
    {
      path: "../assets/fonts/Brandon_blk_it.otf",
      weight: "700",
      style: "italic"
    }
  ]
});

export default function Home() {
  gsap.registerPlugin(ScrollTrigger);

  return (
    <>
      <Head>
        <title>Gaia Box Gourmet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <div className={brandonGrotesque.className}>
        <NavBar />
        <Hero />
        <About /> 
        <Menu menu={menu} />
        <Wine wines={wines} />
        <Events />
        <Contact />
      </div>
    </>
  )
}
